### ISSUE TITLE
Is there a way to generate a previewImage?

### ISSUE THREAD

**Issue by zwily** [zranger1/pixelblaze-client#22]
### Environment

- OS: OS X
- Python: 3
- Pixelblaze: 3.51
- pixelblaze-client: latest

### Minimal reproducible example

If I have some source code and want to compile it and upload the pattern to a PB, it looks like I need: a) the code, b) the bytecode, and c) a previewImage. I know how to generate the first 2, but how can I get a previewImage? Does the PB web app upload the bytecode (from the editor) and then capture frames, and build the previewImage that way? Can I just use a dummy preview image if I don't care what it looks like?

### Expected Behavior

n/a

### Actual Behavior

n/a

### Additional Context

n/a

**Comment by zranger1** [comment]
Hi! The preview image is a jpeg image in which each column is an LED and each row is a frame.  The default dimensions are 100x150.  The webUI does indeed capture preview frames over time to build the image.

You can get the frames from Python if you want, with the getPreviewFrame() method.  The Pixelblaze-client library doesn't have its own jpeg encoder/decoder, so you'll have to use an external library to convert the preview RGB bytes to jpeg.

But there's nothing in there that actually cares about the content of the preview image, so as long as the format is correct, you can pretty much use a JPEG from anywhere for this job.

**Comment by zwily** [comment]
Thanks - that what I suspected. I'll just use a blank image for now.
